# - name: install required system dependencies
#   hosts: all
#   become: yes
#   ignore_errors: true
#   tasks:
#   - name: clean k8s pv/pvc/pods
#     shell: |
#       kubectl get pods --all-namespaces -o wide | grep Evicted | awk '{print $1,$2}' | xargs -L1 kubectl delete pod -n
#       kubectl get pods --all-namespaces -o wide | grep Error | awk '{print $1,$2}' | xargs -L1 kubectl delete pod -n
#       kubectl get pods --all-namespaces -o wide | grep Completed | awk '{print $1,$2}' | xargs -L1 kubectl delete pod -n
#       kubectl describe -A pvc | grep -E "^Name:.*$|^Namespace:.*$|^Used By:.*$" | grep -B 2 "<none>" | grep -E "^Name:.*$|^Namespace:.*$" | cut  -f2 -d: | paste -d " " - - | xargs -n2 bash -c 'kubectl -n ${1} delete pvc ${0}'
#       kubectl get pvc --all-namespaces | tail -n +2 | grep -v Bound | awk '{print $1,$2}' | xargs -L1 kubectl delete pvc -n
#       kubectl get pv | tail -n +2 | grep -v Bound | awk '{print $1}' | xargs -L1 kubectl delete pv

# - name: clean docker 
#   hosts: all
#   become: yes
#   ignore_errors: true
#   tasks:
#   - name: clean docker volume
#     shell: |
#       docker volume prune
#       docker builder prune
#       docker images | grep none | awk '{print $3}' | xargs docker rmi
#       docker volume rm $(docker volume ls -q)
#       docker system prune -f


# - name: clean journalctl  log
#   hosts: masters[0],workers
#   become: yes
#   ignore_errors: true
#   tasks:
#   - name: clean log file
#     shell: |
#       journalctl --vacuum-size=2K
#       df -h /
#       ctr -n k8s.io i ls



- name: clean journalctl  log
  hosts: masters[0],workers
  become: yes
  ignore_errors: true
  tasks:
    - name: Ensure a job that clean unused log
      ansible.builtin.cron:
        name: "remove unused log"
        minute: "0"
        hour: "5,2"
        job: "(/usr/bin/journalctl --vacuum-size=2K)"