- name: generate local ssh private key
  hosts: 127.0.0.1
  become: yes
  connection: local
  ignore_errors: false
  tasks:
    - name: Ensure a job that clean unused log
      openssh_keypair:
        path: id_ssh_ed25519
        type: ed25519
        force: false
    # # 配置免密码登录
    # - name: Add a host in the configuration
    #   community.general.ssh_config:
    #     host: "example.com"
    #     hostname: "github.com"
    #     identity_file: "id_ssh_ed25519"
    #     user: root
    #     port: '22'
    #     state: present


- name: add ssh private key
  hosts: masters[0]
  become: yes
  ignore_errors: false
  tasks:
  - name: Set authorized key taken from file
    ansible.posix.authorized_key:
      user: root
      state: present
      key: "{{ lookup('file', 'id_ssh_ed25519.pub') }}"
  - name: Unarchive a file that is already on the remote machine
    ansible.builtin.unarchive:
      src: /cbs/k8s-yyds/helm/cilium.tgz
      dest: /root
      # remote_src: yes


